### ISSUE TITLE
Error 502 - what?

### ISSUE THREAD

**Issue by epiatros** [opentox/toxcreate#62]
Hi folks, lazar quit service w/ error 502. Any clues why? -H-

You are signed in as 'epiatros' to lazar.in-silico.de, sign out  

--- !ruby/object:OpenTox::ErrorReport 
actor: http://lazar.in-silico.de/predict
errorType: OpenTox::RestCallError
http_code: 502
message: REST call subsequent error
rest_params: 
  :headers: 
    :accept: application/json
    :subjectid: AQIC5wM2LY4SfcwmyuTkrkKuYNpGkxJnYCRLCZmVD-daqYw.*AAJTSQACMDE.*
  :payload: 
    :compound_uri: http://lazar-services.in-silico.ch/compound/InChI=1S/C9H7I2NO5/c1-2(13)12-6-4(10)3(9(16)17)5(11)7(14)8(6)15/h14-15H,1H3,(H,12,13)(H,16,17)
  :rest_uri: http://lazar-services.in-silico.ch/model/23
backtrace: |-
  /home/opentox/opentox-ruby/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/opentox-ruby-3.0.1/lib/rest_client_wrapper.rb:178:in `received_error'
  /home/opentox/opentox-ruby/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/opentox-ruby-3.0.1/lib/rest_client_wrapper.rb:107:in `execute'
  /home/opentox/opentox-ruby/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/opentox-ruby-3.0.1/lib/rest_client_wrapper.rb:31:in `post'
  /home/opentox/opentox-ruby/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/opentox-ruby-3.0.1/lib/model.rb:201:in `run'
  ./application.rb:425:in `POST /predict/?'
  ./application.rb:418:in `each'
  ./application.rb:418:in `POST /predict/?'
errorCause: !ruby/object:OpenTox::ErrorReport 
  actor: http://lazar-services.in-silico.ch/model/23
  errorCause: 
  errorType: NoMemoryError
  http_code: 500
  message: failed to allocate memory
  rest_params: 
  backtrace: |-
    ./lazar.rb:15:in `read'
    ./lazar.rb:15:in `lazar'
    ./lazar.rb:159:in `POST /:id/?'

**Comment by rautenberg** [comment]
Hi, it is up and running again.
